### ISSUE TITLE
Difference with using '+'?

### ISSUE THREAD

**Issue by vangelov** [kiliman/remix-flat-routes#103]
I read the docs several times and did some tests but I still can't understand the difference between this:

```
parent+
├── _layout.tsx
└── child+
    └──index.tsx
```

and this (without `+` ):

```
parent
├── _layout.tsx
└── child
    └──index.tsx
```

**Comment by kiliman** [comment]
The `+` suffix is _hybrid_ routes and is used for nesting. 

Whereas folders **without** the `+` suffix is for _colocation_.


Hybrid routes use the following transformations:
* `parent+/_layout.tsx` => `someroute.tsx`
* `parent+/child.tsx` => `parent.child.tsx`
* `parent+/child+/another.tsx` => `parent.child.another.tsx`
* `parent+/_.child.tsx` => `parent_.child.tsx` (when you don't want child to use parent layout)
* _index_ routes should be named `_index.tsx` (v2 convention), although RFR does support `index.tsx`.
```
parent+
├── _layout.tsx     => parent.tsx
└── child+
    └──_index.tsx    => parent.child._index.tsx
```

and this (without `+` ):

In Remix `v2` routing and `remix-flat-routes` you can use a folder (without `+`) for colocation. The folder name is your route name, and the route module is the file named: `route.tsx`.

Only the leaf route should have a _naked_ folder. Instead of `parent/child/route.tsx` it should be `parent.child/route.tsx`
```
parent
├── _layout.tsx      => parent.tsx
└── child            => technically invalid (folder should only be on leaf route)
    └──index.tsx
parent.child         => this is correct 
├── route.tsx        => v2 convention uses `route.tsx` for route module
                        remix-flat-routes allows index, page, route, layout or anything starting with `_`
```

**Comment by vangelov** [comment]
Thank you for the detailed explanation.
