### ISSUE TITLE
Usage of underscore after 

### ISSUE THREAD

**Issue by MarcosCunhaLima** [kiliman/remix-flat-routes#48]
I understood that placing a trailing underscore, it would ignore the sibling layout file and use the layout of its parent as in the example: 
<img width="928" alt="image" src="https://user-images.githubusercontent.com/818861/230084424-4a4d60e8-2570-40aa-9862-af1744ba3ad8.png">

After in the documentation, there is an example that, IMHO, says other thing:
<img width="902" alt="image" src="https://user-images.githubusercontent.com/818861/230086181-eec1ff64-293c-43f3-8f84-9b07ec5ad0ee.png">

From what I understood of a trailing underscore, `$userId_.edit.tsx` would use root layout, wouldn't it? 

Or how can I use a root layout in this case?

BTW, I am loving using this library, I think in my case it solved a lot of organisation issues placing files in folders!

**Comment by kiliman** [comment]
First of all, thanks for the kind words. I'm glad it's been useful for you.

Your edit route is not using the root layout due to a side effect of using the hybrid (`+`) folders.

The `+` suffix is converted back to its flat-files form before processing.

So `users+/$userId_.edit.tsx` is the same as `users.$userId_.edit.tsx`

Also, another quirk of hybrid routes is that `user+/_layout.tsx` is the same as `users.tsx`.

Therefore, when looking for the parent route, it sees there's a matching `users` layout and uses that.

Essentially, by nesting under the `users+` folder, it means that all child routes will at least use the `_layout` route. 99% of the time, that's probably what you want. But in your case, it's causing an issue.

The current workaround is to move that route outside the `users+` folder and name it `users_.$userId.edit.tsx`. This means don't match the `users` layout and use the root.

A possible solution is to allow you to use `users+/_.$userId.edit.tsx`. Just like `+/` is translated to `.`, we can make `+/_.` translated to `_.` so it'll be `users_.$userId.edit.tsx`, which is what we want (see above).

Anyway, I hope this makes sense.

**Comment by kiliman** [comment]
> Yes, the workaround has solved the problem but, as you may have guessed, created other as now I have "users" routes in two places.

I agree it's not ideal.

> Is it something that should work now or you are just planning something?

I was just suggesting a possible solution. It's not currently implemented, but something I should be able to add.

> One last thing I couldn't grasp: the difference from ending with a + sign and without it as in the example below it seems to generate the same routing (project and users):

That's the difference between `flat-files` and `flat-folders`. In the current `v2` routing, if you use flat-files, you can't have **any** folders, not even for organizations. That's why I added the `+` suffix (hybrid routes), so you can organize your routes in a manageable way.

`flat-folders` is a convention where the folder name is the route, and its contents like *route.tsx* or *index.tsx* is the route module. Any other files are ignored. This way you can colocate other files like components, images, CSS, etc.

**Comment by MarcosCunhaLima** [comment]
OK @kiliman Thank you, nevertheless I will keep using this library as I think is a step forward organisation then flat-files for big projects.
